name: ci
on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    env:
      BATON_LOG_LEVEL: debug
      BATON_ENVIRONMENT: "test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Build baton-trello
        run: go build ./cmd/baton-trello
      - name: Run baton-trello
        run: ./baton-trello --api-key=${{ secrets.BATON_API_KEY }} --api-token=${{ secrets.BATON_API_TOKEN }} --organizations=${{ secrets.BATON_ORGANIZATIONS }}
